<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerMK20xx8\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerMK20xx8/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerMK20xx8.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerMK20xx8\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerMK20xx8\App_KernelDevDebugContainer([
    'container.build_hash' => 'MK20xx8',
    'container.build_id' => '4947b7c6',
    'container.build_time' => 1586282321,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerMK20xx8');
