<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerPPk81Le\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerPPk81Le/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerPPk81Le.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerPPk81Le\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerPPk81Le\App_KernelDevDebugContainer([
    'container.build_hash' => 'PPk81Le',
    'container.build_id' => 'f5905d1f',
    'container.build_time' => 1586330446,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerPPk81Le');
